# ?? ?? ??
# Eureka -> Web Service ??? ???
server:
  port: 8761

# ???? ???? ???? ??? ????
# ??? ???? ???? ??? ID? ?????
# ??? discoveryservice? ??? ?
spring:
  application:
    name: discoveryservice

# eureka ????? ??
# eureka ?????? ???? Spring boot? ??? ??
# client?? ???? ??? ???? ?.

# register-with-eureka, fetch-registry ? defalut? True?
# ?? ??? ???? ??? ?????.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false